apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::281789399995:role/eksctl-sre-demo-addon-iamserviceaccount-kube--Role1-U6NZBEx00vzo
