apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 23.4.0

    helm:
      values: |
        server:
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "8Gi"
              cpu: "2000m"
          persistentVolume:
            enabled: true
            storageClass: prometheus-storage
            size: 50Gi
          replicaCount: 1
          retention: "15d"

        serviceAccounts:
          server:
            create: true
            name: prometheus-server
            annotations:
              eks.amazonaws.com/role-arn: "arn:aws:iam::281789399995:role/cloudwatch-observability"

        alertmanager:
          enabled: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          persistentVolume:
            enabled: true
            storageClass: gp3
            size: 5Gi
          replicaCount: 1

        nodeExporter:
          enabled: true

        pushgateway:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
